import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Project App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='min-h-screen'>
					<Navbar />
					{children}
				</div>
			</body>
		</html>
	)
}
